import chromadb
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

# Create a ChromaDB client that saves data to disk (persists between runs)
chroma_client = chromadb.PersistentClient(path="./chroma_db")

# Create (or get, if it already exists) a collection
collection = chroma_client.get_or_create_collection(name="test_collection")

# Some sample chunks
chunks = [
    "Muscle spindles detect changes in muscle length and speed of stretch.",
    "Golgi tendon organs sense tension generated by muscle contraction.",
    "The stock market closed higher today after strong earnings reports.",
    "Pacinian corpuscles respond to vibration and deep pressure in the skin."
]

# Generate embeddings for all chunks at once
embeddings = model.encode(chunks).tolist()  # ChromaDB wants plain lists, not numpy arrays

# Add to the collection — each chunk needs a unique id
collection.add(
    documents=chunks,
    embeddings=embeddings,
    ids=[f"chunk_{i}" for i in range(len(chunks))]
)

print(f"Added {len(chunks)} chunks to the collection.")

# Now let's query it with a question
question = "How does the body sense muscle tension?"
question_embedding = model.encode([question]).tolist()

results = collection.query(
    query_embeddings=question_embedding,
    n_results=2  # top 2 most similar chunks
)

print(f"\nQuestion: {question}")
print("Top matching chunks:")
for doc in results["documents"][0]:
    print(" -", doc)
